@Library('pipeline-library') _
pipeline {
  agent {
    kubernetes {
      yaml '''
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.5.4-jdk-8-slim
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
'''
      defaultContainer 'maven'
    }
  }

    stages {
        stage('define agent') {
      steps {
        echo "${agentType}"
      }
        }
        stage('Checkout') {
      steps {
        // git credentialsId: "${github_creds}" , url: "${github_repo}"
        checkout([$class: 'GitSCM',
                              branches: [[name: '*/master']],
                              extensions: [],
                              userRemoteConfigs: [[credentialsId: "${github_creds}", url: "${github_repo}" ]]])
      }
        }
        stage('Build') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
        }
    }

    post {
      success {
      sh 'echo "SUCCESSFUL BUILD, sending  email ..."'
      }

      failure {
        sh 'echo "FAILED BUILD, sending  email ..."'
      }
    }
}
