@Library('pipeline-library') _

javaMaven  

/**
pipeline {

configAgent 

    stages {
        stage('define agent') {
      steps {
        echo "${agentType}"
      }
        }
        stage('Checkout') {
      steps {
        // git credentialsId: "${github_creds}" , url: "${github_repo}"
        checkout([$class: 'GitSCM',
                              branches: [[name: '*\/main']],
                              extensions: [],
                              userRemoteConfigs: [[credentialsId: "${github_creds}", url: "${github_repo}" ]]])
      }
        }
        stage('Build') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
        }
    }

    post {
      success {
      sh 'echo "SUCCESSFUL BUILD, sending  email ..."'
      }

      failure {
        sh 'echo "FAILED BUILD, sending  email ..."'
      }
    }
}
*/
